name: Project Feedback

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  Project-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      #Make file Executable
      - name: File Executable
        id: pr_feedback
        run: chmod +x ./testing/project/tests.sh

      #Run Automated Tests
      - name: Project Automated Testing
        id: pr_feedback1
        run: ./testing/project/tests.sh
